# Generated by Django 5.2 on 2025-04-27 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profesor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
                'unique_together': {('nombre', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='ProfesorEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='personal.especialidad')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='personal.profesor')),
            ],
            options={
                'verbose_name': 'Especialidad de Profesor',
                'verbose_name_plural': 'Especialidades de Profesores',
                'db_table': 'profesor_especialidad',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('profesor', 'especialidad')},
            },
        ),
    ]
