# Generated by Django 5.2 on 2025-04-27 00:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autoevaluación',
                'verbose_name_plural': 'Autoevaluaciones',
                'db_table': 'auto_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='DimensionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('EXA', 'Examen'), ('TAR', 'Tarea'), ('PRO', 'Proyecto'), ('PAR', 'Participación'), ('OTR', 'Otro')], default='OTR', max_length=3)),
                ('ponderacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Dimensión de Evaluación',
                'verbose_name_plural': 'Dimensiones de Evaluación',
                'db_table': 'dimension_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='NotaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_obtenida', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nota de Actividad',
                'verbose_name_plural': 'Notas de Actividades',
                'db_table': 'nota_actividad',
            },
        ),
        migrations.CreateModel(
            name='NotaFinalMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('APR', 'Aprobado'), ('REP', 'Reprobado'), ('INC', 'Incompleto')], default='INC', max_length=3)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota Final de Materia',
                'verbose_name_plural': 'Notas Finales de Materias',
                'db_table': 'nota_final_materia',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('es_recuperacion', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('materia_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.materiacurso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
