# Generated by Django 5.2 on 2025-04-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('calendario', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('evaluacion', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='personal.profesor'),
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluaciones', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='materia_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluaciones', to='academico.materiacurso'),
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluaciones', to='calendario.periodo'),
        ),
        migrations.AddField(
            model_name='dimensionevaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='calendario.periodo'),
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluaciones', to='evaluacion.dimensionevaluacion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='evaluacion.dimensionevaluacion'),
        ),
        migrations.AddField(
            model_name='notaactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='evaluacion.actividad'),
        ),
        migrations.AddField(
            model_name='notaactividad',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_actividades', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='notafinalmateria',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_finales', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='notafinalmateria',
            name='materia_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_finales', to='academico.materiacurso'),
        ),
        migrations.AddField(
            model_name='notafinalmateria',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_finales', to='calendario.periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='dimensionevaluacion',
            unique_together={('periodo', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='autoevaluacion',
            unique_together={('estudiante', 'materia_curso', 'periodo', 'dimension')},
        ),
        migrations.AlterUniqueTogether(
            name='notaactividad',
            unique_together={('actividad', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='notafinalmateria',
            unique_together={('estudiante', 'materia_curso', 'periodo')},
        ),
    ]
