# Generated by Django 5.2 on 2025-04-27 00:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colegios/logos/')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'colegio',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_aulas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modulo',
            },
        ),
        migrations.CreateModel(
            name='UnidadEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sie', models.CharField(max_length=50, unique=True, verbose_name='Código SIE')),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('COMPLETO', 'Jornada Completa')], max_length=10)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_educativas', to='institucion.colegio')),
            ],
            options={
                'verbose_name': 'Unidad Educativa',
                'verbose_name_plural': 'Unidades Educativas',
                'db_table': 'unidad_educativa',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('AUL', 'Aula Regular'), ('LAB', 'Laboratorio'), ('TAL', 'Taller'), ('AUD', 'Auditorio'), ('COM', 'Sala de Computación'), ('GIM', 'Gimnasio'), ('BIB', 'Biblioteca')], default='AUL', max_length=3)),
                ('equipamiento', models.TextField(blank=True, null=True)),
                ('piso', models.PositiveSmallIntegerField(default=1)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='institucion.modulo')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aula',
                'unique_together': {('modulo', 'nombre')},
            },
        ),
    ]
