# Generated by Django 5.2 on 2025-05-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_unidadeducativa_nivel_unidadeducativa_nombre'),
        ('usuarios', '0007_alter_superadmin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='super_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colegios', to='usuarios.admin'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='modulo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulos', to='institucion.colegio'),
        ),
        migrations.AddField(
            model_name='unidadeducativa',
            name='admin_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_educativas', to='usuarios.admin'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='institucion.modulo'),
        ),
        migrations.AlterField(
            model_name='unidadeducativa',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_educativas', to='institucion.colegio'),
        ),
    ]
