# Generated by Django 5.2 on 2025-05-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_colegio_super_admin_modulo_modulo_fk_and_more'),
        ('usuarios', '0007_alter_superadmin_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='super_admin',
        ),
        migrations.AddField(
            model_name='colegio',
            name='super_admin_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colegios', to='usuarios.superadmin'),
        ),
    ]
