# Generated by Django 5.2 on 2025-05-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_remove_colegio_super_admin_colegio_super_admin_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='modulo_fk',
            new_name='colegio_fk',
        ),
    ]
