# Generated by Django 5.2 on 2025-04-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFeriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_nacional', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Feriado',
                'verbose_name_plural': 'Tipos de Feriados',
                'db_table': 'tipo_feriado',
            },
        ),
        migrations.CreateModel(
            name='TipoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Horario',
                'verbose_name_plural': 'Tipos de Horarios',
                'db_table': 'tipo_horario',
            },
        ),
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('unidad_educativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='institucion.unidadeducativa')),
            ],
            options={
                'verbose_name': 'Calendario Académico',
                'verbose_name_plural': 'Calendarios Académicos',
                'db_table': 'calendario_academico',
                'ordering': ['-año'],
                'unique_together': {('unidad_educativa', 'año')},
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_division', models.CharField(choices=[('SEM', 'Semestre'), ('TRI', 'Trimestre'), ('BIM', 'Bimestre'), ('CUA', 'Cuatrimestre'), ('OTR', 'Otro')], max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLA', 'Planificado'), ('CUR', 'En Curso'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='PLA', max_length=3)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='calendario.calendarioacademico')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'db_table': 'periodo',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='calendario.calendarioacademico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feriados', to='calendario.tipoferiado')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'feriado',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='calendario.tipohorario')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ClaseHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.clase')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='calendario.horario')),
            ],
            options={
                'verbose_name': 'Horario de Clase',
                'verbose_name_plural': 'Horarios de Clases',
                'db_table': 'clase_horario',
                'unique_together': {('clase', 'horario')},
            },
        ),
    ]
