# Generated by Django 5.2 on 2025-04-27 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('parentesco', models.CharField(choices=[('PAD', 'Padre'), ('MAD', 'Madre'), ('TUT', 'Tutor Legal'), ('HER', 'Hermano/a'), ('OTR', 'Otro')], default='OTR', max_length=3)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutor',
                'ordering': ['usuario__apellido', 'usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rude', models.CharField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
                'ordering': ['usuario__apellido', 'usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TutorEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='estudiantes.estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='estudiantes.tutor')),
            ],
            options={
                'verbose_name': 'Relación Tutor-Estudiante',
                'verbose_name_plural': 'Relaciones Tutor-Estudiante',
                'db_table': 'tutor_estudiante',
                'ordering': ['-es_principal', 'fecha_asignacion'],
                'unique_together': {('tutor', 'estudiante')},
            },
        ),
    ]
