# Generated by Django 5.2 on 2025-04-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('capacidad_maxima', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Paralelo',
                'verbose_name_plural': 'Paralelos',
                'db_table': 'paralelo',
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educativo', models.CharField(choices=[('INI', 'Educación Inicial'), ('PRI', 'Educación Primaria'), ('SEC', 'Educación Secundaria')], max_length=3)),
                ('unidad_educativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='institucion.unidadeducativa')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'grado',
                'unique_together': {('unidad_educativa', 'nivel_educativo')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('paralelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='curso', serialize=False, to='academico.paralelo')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.AddField(
            model_name='paralelo',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='academico.grado'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.aula', verbose_name='Aula asignada')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso', verbose_name='Curso relacionado')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
            },
        ),
        migrations.AlterUniqueTogether(
            name='paralelo',
            unique_together={('grado', 'letra')},
        ),
        migrations.CreateModel(
            name='MateriaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academico.materia')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Materia por Curso',
                'verbose_name_plural': 'Materias por Curso',
                'db_table': 'materia_curso',
                'unique_together': {('curso', 'materia')},
            },
        ),
    ]
