# Generated by Django 5.2 on 2025-04-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaclase',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_clases', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='asistenciageneral',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_generales', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='comportamiento',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportamientos', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias', to='estudiantes.tutor'),
        ),
        migrations.AddField(
            model_name='asistenciaclase',
            name='licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='asistencia.licencia'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciageneral',
            unique_together={('estudiante', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaclase',
            unique_together={('clase', 'estudiante', 'fecha')},
        ),
    ]
