# Generated by Django 5.2 on 2025-04-28 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(verbose_name='Hora de entrada')),
                ('hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de sesión',
                'verbose_name_plural': 'Bitácoras de sesión',
                'db_table': 'bitacora_sesion',
                'ordering': ['-hora_entrada'],
            },
        ),
    ]
