# Generated by Django 5.2 on 2025-05-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ppassword_reset_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
