# Generated by Django 5.2 on 2025-05-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ppassword_reset_pin',
            new_name='password_reset_pin',
        ),
    ]
