# Generated by Django 5.2 on 2025-05-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_ppassword_reset_pin_usuario_password_reset_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmin',
            options={'verbose_name': 'Super Administrador', 'verbose_name_plural': 'Super Administraadores'},
        ),
    ]
