# Generated by Django 5.2 on 2025-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_superadmin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
    ]
