# Generated by Django 5.2 on 2025-05-07 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_bitacora_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('ver', 'Ver'), ('otro', 'Otro')], default='otro', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='tabla',
            field=models.CharField(default='general', max_length=100, verbose_name='Tabla afectada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
